# Generated by Django 3.1.3 on 2021-09-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0003_auto_20210917_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='bg_image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
