# Generated by Django 3.1.3 on 2021-09-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0004_list_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='bg_image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
