# Generated by Django 3.1.3 on 2021-09-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0005_auto_20210917_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='bg_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
