# Generated by Django 3.1.3 on 2021-09-18 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0007_list_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=255),
        ),
    ]
